### ISSUE TITLE
Issue with multiprocess or urllib?

### ISSUE THREAD

**Issue by asafpelegcodes** [wolever/nose-parameterized#20]
I'm potentially having two sets of issues.

First is that I'm getting the following failure when I run my suite with the nose multiprocess plugin and I have a parameterized test with more than 1 set of injected params.  If I add more than one set of injected params I see an issue

Failure: TypeError (unbound method address() must be called with Failure instance as first argument (got nothing instead)) ... ERROR

The second issue is that my test suite just hangs, it gets stuck and never executes to completion.

Any advice?

**Comment by wolever** [comment]
Would you be able to post the problem, including the code that's failing, to StackOverflow, then link to it here? That'll be a better venue for debugging this, I think. Thanks!

**Comment by asafpelegcodes** [comment]
I can't really post all my code since its proprietary to my company but I
can post some sample code if you think that would be sufficient.

**Comment by wolever** [comment]
Then at very least a sample which will reproduce the issue. The problem you're describing is fairly broad and could be caused by a few things.

**Comment by asafpelegcodes** [comment]
fair enough, thanks
