### ISSUE TITLE
Parameters are not shown in nose output if doc strings are used.

### ISSUE THREAD

**Issue by torfuspolymorphus** [wolever/nose-parameterized#27]
If a test function has a doc string then nose uses that doc string instead of the function name in its verbose output:

    def test():
        """
        A test.
        """
        pass

yields

```
A test. ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

If this feature is used in combination with `parameterized` then each parameterized variant of a test case is reported using the same output (the raw doc string), instead of the "parameterized" output that is used when no doc string is present:

```
from nose_parameterized import parameterized

@parameterized([(1, 1), (2, 2)])
def test1(a, b):
    """
    First test.
    """
    assert a == b


@parameterized([(1, 1), (2, 2)])
def test2(a, b):
    assert a == b
```

yields

```
First test. ... ok
First test. ... ok
nosedemo.test2(1, 1) ... ok
nosedemo.test2(2, 2) ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK
```

I would have expected something like 
```
First test. (1, 1) ... ok
First test. (2, 2) ... ok
```

This may be due to nose's behavior w.r.t. doc strings and test generators:

```
def test():
    """
    A test.
    """
    def check(a, b):
        assert a == b
    for case in [(1, 1), (2, 2)]:
        yield check, case[0], case[1]
```

yields

```
A test. ... ok
A test. ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK
```

**Comment by torfuspolymorphus** [comment]
For anyone who's also running into this, here's a quick workaround:

```
import functools
from nose_parameterized import parameterized

def parameterized2(*pargs, **pkwargs):
    """
    Patched version of ``parameterized`` to support adding params to doc strings.
    """
    def decorator(f):
        f = parameterized(*pargs, **pkwargs)(f)
        @functools.wraps(f)
        def wrapper(*args, **kwargs):
            for case in f(*args, **kwargs):
                if f.__doc__:
                    wrapper.__doc__ = f.__doc__.strip() + ' %r' % (case[1:],)
                yield case
        return wrapper
    return decorator


@parameterized2([(1, 1), (2, 2)])
def test(a, b):
    """
    A test.
    """
    assert a == b
```

yields

```
A test. (1, 1) ... ok
A test. (2, 2) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK
```

**Comment by wolever** [comment]
This functionality actually exists in `@parameterized.expand`, and I'm not sure why I didn't include that in regular parameterized functions too. I've added that in 857afd3dc3394fe640174518c0994efd75995965 for  (current master), though — can you give that a try and see if it works for you?

**Comment by torfuspolymorphus** [comment]
Thanks for your quick reaction on this!

Your update (857afd3) does include the params in the output, but it omits the doc string (both with `parameterized` and `parameterized.expand`):

```
@parameterized([(1, 1), (2, 2)])
def test1(a, b):
    """
    A test.
    """
    assert a == b


@parameterized([(1, 1), (2, 2)])
def test2(a, b):
    assert a == b


@parameterized.expand([(1, 1), (2, 2)])
def test3(a, b):
    """
    Another test.
    """
    assert a == b


@parameterized.expand([(1, 1), (2, 2)])
def test4(a, b):
    assert a == b
```

yields

```
[with a=1, b=1] ... ok
[with a=2, b=2] ... ok
nosedemo.test2(1, 1) ... ok
nosedemo.test2(2, 2) ... ok
[with a=1, b=1] ... ok
[with a=2, b=2] ... ok
nosedemo.test4_0 ... ok
nosedemo.test4_1 ... ok

----------------------------------------------------------------------
Ran 8 tests in 0.004s

OK
```

Looking through the code I think the problem is in `default_doc_func`: To get the first line you do a `func.__doc__.partition("\n")`, but since my doc strings start with a newline after the quotes all that gives you is an empty string.

[PEP 257](https://www.python.org/dev/peps/pep-0257/) says that (emphasis mine)

> Multi-line docstrings consist of a summary line just like a one-line docstring, followed by a blank line, followed by a more elaborate description. The summary line may be used by automatic indexing tools; it is important that it fits on one line and is separated from the rest of the docstring by a blank line. **The summary line may be on the same line as the opening quotes or on the next line.** The entire docstring is indented the same as the quotes at its first line (see example below). 

Hence I suggest using `func.__doc__.lstrip().partition("\n")` instead. That gives the expected results in my tests.

**Comment by wolever** [comment]
Ah, right! Because it considers the first actual line of the docstring, not the first logical line.

Give 4fd04b8 a try — it strips leading whitespace from the docstring before determining the first line (which is, I think, the way Nose does it too).

On 2015-08-06, at 8:06 AM, Torf <notifications@github.com> wrote:

> Thanks for your quick reaction on this!
> 
> Your update (857afd3) does include the params in the output, but it omits the doc string (both with parameterized and parameterized.expand):
> 
> @parameterized([(1, 1), (2, 2)])
> def test1(a, b):
>     """
>     A test.
>     """
>     assert a == b
> 
> 
> @parameterized([(1, 1), (2, 2)])
> def test2(a, b):
>     assert a == b
> 
> 
> @parameterized.expand([(1, 1), (2, 2)])
> def test3(a, b):
>     """
>     Another test.
>     """
>     assert a == b
> 
> 
> @parameterized.expand([(1, 1), (2, 2)])
> def test4(a, b):
>     assert a == b
> yields
> 
> [with a=1, b=1] ... ok
> [with a=2, b=2] ... ok
> nosedemo.test2(1, 1) ... ok
> nosedemo.test2(2, 2) ... ok
> [with a=1, b=1] ... ok
> [with a=2, b=2] ... ok
> nosedemo.test4_0 ... ok
> nosedemo.test4_1 ... ok
> 
> ----------------------------------------------------------------------
> Ran 8 tests in 0.004s
> 
> OK
> Looking through the code I think the problem is in default_doc_func: To get the first line you do a func.__doc__.partition("\n"), but since my doc strings start with a newline after the quotes all that gives you is an empty string.
> 
> PEP 257 says that (emphasis mine)
> 
> Multi-line docstrings consist of a summary line just like a one-line docstring, followed by a blank line, followed by a more elaborate description. The summary line may be used by automatic indexing tools; it is important that it fits on one line and is separated from the rest of the docstring by a blank line. The summary line may be on the same line as the opening quotes or on the next line. The entire docstring is indented the same as the quotes at its first line (see example below).
> 
> Hence I suggest using func.__doc__.lstrip().partition("\n") instead. That gives the expected results in my tests.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
phone: (416) 906-0403
pgp: B230230D

**Comment by torfuspolymorphus** [comment]
Using the same tests as above, 4fd04b8 produces the expected result.

Thanks for the quick responses on this!
