### ISSUE TITLE
Instance variables

### ISSUE THREAD

**Issue by bee-keeper** [wolever/nose-parameterized#28]
```python
class SomeTest(TestCase):
    @parameterized.expand([
        {'something': self.something},
        {'something_else': self.something_else},
    )]
    def test_something(self, user):
        pass
```

Hi there, am wondering about using instance variables with nose-parameterized?  Have you any ideas or opinions about this? Edit: Obviously the code above won't compile, it's just to illustrate the use case ;)

Thanks,

**Comment by wolever** [comment]
As it stands (and as I’m sure you’ve figured out) there is no way to use instance variables.

It’s not something I’m necessarily opposed to adding, though. Could you tell me a bit more about how you’d use instance variables if you could, and how that would be preferable to other alternatives?

> On Aug 16, 2015, at 11:31 AM, bee-keeper <notifications@github.com> wrote:
> 
> class SomeTest(TestCase):
>     @parameterized.expand([
>         {'something': self.something},
>         {'something_else': self.something_else},
>     )]
>     def test_something(self, user):
>         pass
> Hi there, am wondering about using instance variables with nose-parameterized? Have you any ideas or opinions about this?
> 
> Thanks,
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/wolever/nose-parameterized/issues/28>.
> 

--
phone: (416) 906-0403
pgp: B230230D

**Comment by bee-keeper** [comment]
Thanks for the quick reply on this one.  I'm not sure if it's about instance variables being preferable but more that it could perhaps be useful to support them as well?

I had a little look at implementing this yesterday but it doesn't look as clear cut as i first thought.  Feel free to close the issue and if there is future support for the idea it might be worth revisiting?

**Comment by wolever** [comment]
Okay :) Yea, I'm definitely not opposed to the idea. But I'd rather not introduce new features without some clear use cases. Please feel free to re-open this if you come up with some.
