### ISSUE TITLE
Add type hints or type stubs

### ISSUE THREAD

**Issue by smessmer** [wolever/nose-parameterized#36]
Could you add type hints or type stubs (PEP484) to nose-parameterized?

**Comment by wolever** [comment]
Hey,

I'm not opposed to adding type hints, but it would need to be done in a Python 2 compatible way. If you want to propose something I'd be happy to give you feedback!

**Comment by wolever** [comment]
Closing this issue out for now. Please feel free to re-open if you've got a proposal!
