### ISSUE TITLE
Quation : skip only one parameter from the parameterized list

### ISSUE THREAD

**Issue by islamTaha12** [wolever/nose-parameterized#38]
**Description**
As I understand, parameterized.expand([1, 2, 3]) will create three testcases. I would like to know how can I skip only one of them.

I know that @unitest.skip() will skip the whole 3 test case, I only wanna to skip one of them.

**Comment by wolever** [comment]
You can raise a `SkipTest` exception to skip the test: https://docs.python.org/2/library/unittest.html#unittest.SkipTest

**Comment by islamTaha12** [comment]
Thanks
