### ISSUE TITLE
Problems to install from pypi under python X.Y (due to misspelling package name)

### ISSUE THREAD

**Issue by vlcinsky** [wolever/nose-parameterized#39]
In clear virtualenv with python 2.7.12 I had problems to install the package.

Filling this issue it turned out, I misspelled the module name omitting one "e":

```bash
(py27)$ pip install nose-parametrized
Collecting nose-parametrized
  Could not find a version that satisfies the requirement nose-parametrized (from versions: )
No matching distribution found for nose-parametrized
```

Using correct name works:
```bash
(py27)$ pip install nose-parameterized
Collecting nose-parameterized
  Using cached nose_parameterized-0.5.0-py2.py3-none-any.whl
Installing collected packages: nose-parameterized
Successfully installed nose-parameterized-0.5.0
```

It might confuse other people too.

**Comment by wolever** [comment]
Ohh thanks! Do you know of some way to setup PyPI to warn about incorrect package names?

I'll ask around and see if there's a good solution too.

**Comment by vlcinsky** [comment]
PyPi seems quite poor in searching for what you want to get (e.g. trying to search for a package knowing exact name brings a lot of other results and the real hit is buried somewhere down).

People might run into trouble with installation, google for possible solution and possibly find this issue.

But there might be other pypi magic which I am not aware of.

**Comment by wolever** [comment]
Done! https://pypi.python.org/pypi/nose-parametrized/0.0

**Comment by vlcinsky** [comment]
Nice trick - will remember.

Tested and works well on both python 2.7 and 3.5.
